### ISSUE TITLE
Resolver can't be found - version 1.1 needed

### ISSUE THREAD

**Issue by sebastienbonami** [Graylog2/play2-graylog2#11]
Hi,

I use Play 2.2.3 and I want to use this module for sending application logs to Graylog2. As I see here: https://graylog2.github.io/play2-graylog2/index.html, I need version 1.1. The problem is the resolver http://graylog2.github.io/play2-graylog2/releases/ doesn't work and 1.1 is not in the Maven Central Repository.

Thanks for your help.

**Comment by kroepke** [comment]
Hi!

What error do you get?
I think there's a typo in the index.html (http:// is duplicated).

When I use the full url everything works for me.

**Comment by kroepke** [comment]
The actual files are here: https://github.com/Graylog2/play2-graylog2/tree/gh-pages/releases/org.graylog2/play2-graylog2_2.10

**Comment by sebastienbonami** [comment]
Thanks @kroepke, my issue was due to the URL typo. Also, I use *build.sbt* and the correct syntax to add the resolvers is:
<pre><code>resolvers ++= Seq(
  Resolver.url("Graylog2 Play Repository", url("http://graylog2.github.io/play2-graylog2/releases/"))(Resolver.ivyStylePatterns),
  Resolver.url("Graylog2 Play Snapshot Repository", url("http://graylog2.github.io/play2-graylog2/snapshots/"))(Resolver.ivyStylePatterns)
)</code></pre>

The *index.html* documentation should be updated.

**Comment by joschi** [comment]
@sebastienbonami Awesome, thanks for the update! I've updated the docs accordingly.

**Comment by sebastienbonami** [comment]
Ok @joschi. However, I think the previous syntax was good for *Build.scala*. So, both should be in the *index.html* documentation.

**Comment by joschi** [comment]
@sebastienbonami I've added back the lines.
